sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
# might be useful to push reports to an S3 bucket
#  artifacts:
#    paths:
#      - $(find $HOME -name surefire-reports | tr "\n" ":")
#      - $(find $HOME -name failsafe-reports | tr "\n" ":")
#  s3_region: 'us-west-2'
services:
  - redis-server
cache:
  directories:
    - $HOME/.m2
env:
  - REDIS_HOSTNAME=localhost COUCHDB_HOSTNAME=localhost CASSANDRA_VERSION=2.2.5 CASSANDRA_HOSTNAME=localhost
install:
  - sudo apt-get install -qq couchdb
  - bash travis/setup-cassandra.sh 2>&1 > cassandra.log
  # The Maven install provided by Travis is outdated, use Maven wrapper to get the latest version
  - mvn -N io.takari:maven:wrapper
  - ./mvnw -v
  # first run to download all the Maven dependencies without logging
  - travis_wait ./mvnw -B -q -s settings-example.xml -Ptest -DskipTests=true install
  # we run checkstyle first to fail fast if there is a styling error
  - ./mvnw -s settings-example.xml checkstyle:check
before_script:
script:
  - ./mvnw -s settings-example.xml -Ptest -Dmaven.javadoc.skip=true clean install
after_script:
  - rm -rf $HOME/.m2/repository/org/hibernate/ogm/
